services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v23.3.10
    container_name: redpanda
    command:
      - redpanda start
      - --overprovisioned
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --node-id 0
      - --check=false

      # Kafka ports (LISTEN + ADVERTISE)
      - --kafka-addr=PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr=PLAINTEXT://redpanda:9092

      # RPC (required)
      - --rpc-addr=0.0.0.0:33145
      - --advertise-rpc-addr=redpanda:33145

      # Pandaproxy (optional but useful)
      - --pandaproxy-addr=0.0.0.0:8082
      - --advertise-pandaproxy-addr=redpanda:8082

    ports:
      - "9092:9092"
      - "9644:9644"
      - "8082:8082"
    networks:
      - kafka-net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - redpanda
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: redpanda
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: redpanda:9092
      KAFKA_CLUSTERS_0_READONLY: false
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge
