#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "ESLint check..."
npm run lint || exit 1

echo "Prettier format..."
npm run format || exit 1

echo "TypeScript noEmit check..."
npm run tsc-check || exit 1

echo "Building project..."
npm run build || exit 1

echo "All checks passed!"
